Repo to review
wpiesiak/CSS02 pull request #1
Opened 2020-03-06 13:09 UTC by wpiesiak

2020-10-18 17:30 UTC, ArekJanik commented
A few tweaks in terms of how it looks:
* Distorted background proportions:
![Screenshot 2020-10-18 at 19 21 55](https://user-images.githubusercontent.com/2543423/96375216-e1ae2980-1177-11eb-87d2-7ab1b5dcbad9.png)
* White text on white bg
![_Users_janek_Downloads_CSS02-master_index html(iPhone 5_SE)](https://user-images.githubusercontent.com/2543423/96375235-fb4f7100-1177-11eb-9bcc-ee8e11982f05.png)
* Missing buttons on mobile:
![_Users_janek_Downloads_CSS02-master_index html(iPhone 5_SE) (1)](https://user-images.githubusercontent.com/2543423/96375265-2934b580-1178-11eb-9c8a-717c9ff60a5e.png)
* Also please have a look at this section, and make your implementation a bit closer to it (button, avatar + some more styling on the 3 buttons)
![Screenshot 2020-10-18 at 19 23 27](https://user-images.githubusercontent.com/2543423/96375268-30f45a00-1178-11eb-9427-0377ef966f6a.png)

2020-10-20 19:01 UTC, ArekJanik requested changes
Without adding more specific feedback:
* remove the unnecessary wrappers throughout the file, as exampled in the header section,
* use defined variables for spacings/font sizes/etc. instead of random ones,
* use Selleo's BEM correctly,
* use classnames, don't style by tags,
* keep 1 empty line at the end of file

2020-10-20 19:01 UTC, ArekJanik commented on index.html
> +    <link href="https://cdn.iconmonstr.com/1.3.0/css/iconmonstr-iconic-font.min.css" rel="stylesheet" type="text/css">
Why the fonticons if you're using svgs?

2020-10-20 19:01 UTC, ArekJanik commented on index.html
> +    </div>
All classnames seem not related to each other, but they should be (BEM). `logo-container` and `company-name-container` are not defined, and they're unnecessary wrappers.

2020-10-20 19:01 UTC, ArekJanik commented on index.html
> +    <div class="topnav" id="topnav">
What would be the proper semantic tag here?

2020-10-20 19:01 UTC, ArekJanik commented on index.html
> +        <div class="topnav__menu-icon" id="menu-icon">
All these div wrappers are unnecessary, only for the avatar you can use a link wrapper. 
Regarding classnames, eg. `topnav__flight-status-button topnav__element link` a simple `topnav__link` should be sufficient. I see that `topnav__flight-status-button` again is not used anywhere, so please do a cleanup first.

2020-10-20 19:01 UTC, ArekJanik commented on index.html
> +            <div class="tab">
These should be clickable elements

2020-10-20 19:01 UTC, ArekJanik commented on index.html
> +                <h3 class="dot">.</h3>
A `h3` should not contain only a dot. Also the dot should be drawn with CSS, not as a character.

2020-10-20 19:01 UTC, ArekJanik commented on index.html
> +        <h1 class="header-main header--higher">Bangkok</h1>
Get familiar with this one :) https://gist.github.com/ArekJanik/0f2a101935aed483782c15f2d5b73273

2020-10-20 19:01 UTC, ArekJanik commented on index.html
> +                        class="icon--arrow"
This is not BEM - a modifier cannot exist by itself, in this case `button-confirm__icon` is ok

2020-10-20 19:01 UTC, ArekJanik commented on index.html
> +                        height="24"
More details on using SVG's are on Independent 1, but just an FYI: use CSS for sizing, so these properties can be removed.

2020-10-20 19:01 UTC, ArekJanik commented on index.html
> +        <div class="card card__business">
Not BEM - cannot be parent and child at the same time

2020-10-20 19:01 UTC, ArekJanik commented on index.html
> +        <div class="card card__AR">
lowercase

2020-10-20 19:01 UTC, ArekJanik commented on index.html
> +    <div class="experience__element_container">
no underscores, except for the double ones to indicate child element

2020-10-20 19:01 UTC, ArekJanik commented on sass/_variables.sass
> +$white30: rgba(250, 252, 247, .3)
There is absolutely no way to know which of these is lighter/brighter looking at the variable name, they are also inconsisten (`light50` vs `white30`). Have a look at the sample provided [in repo](https://github.com/Selleo/SASS-boilerplate/blob/master/app/assets/stylesheets/base/_variables.sass), you can either:
* use the material design approach with `$color-gray-500` as base and then lighter/darker +/-100, 
* or more descriptive naming, as `$color-gray-base` and then `$color-gray-dark/er/est`

2020-10-20 19:01 UTC, ArekJanik commented on sass/body.sass
> +
We need moar returns at the end of file :P

2020-10-20 19:01 UTC, ArekJanik commented on sass/body.sass
> +@import './_variables'
var import belongs only in the main file, that imports all other files

2020-10-20 19:01 UTC, ArekJanik commented on sass/body.sass
> +  font-size: 11px
This is way too small and not a variable

2020-10-20 19:01 UTC, ArekJanik commented on sass/buttons.sass
> +  &-group div
* don't break classnames, only for `&__child-elements`
* don't style tags, except for general rules
* and absolutely no floats, except for what they were made for

2020-10-20 19:01 UTC, ArekJanik commented on sass/forms.sass
> +  font: normal normal normal 17px "iconmonstr-iconic-font"
nope :)

2020-10-20 19:01 UTC, ArekJanik commented on sass/forms.sass
> +  -webkit-appearance: none
✂️

2021-03-16 14:48 UTC, ArekJanik requested changes
Very nicely recreated design 👍  You mostly need to work on proper scoping/naming components, as this is a little messy.

2021-03-16 14:48 UTC, ArekJanik commented on sass/_variables.sass
> +$background-color: #fafcf7
What if you want to use that var for something other than background-color? 
It's a duplicate of `$light`.

2021-03-16 14:48 UTC, ArekJanik commented on sass/_variables.sass
> +$white30: rgba(250, 252, 247, .3)
Still valid

2021-03-16 14:48 UTC, ArekJanik commented on sass/_variables.sass
> +$backgroundImageMobile: url('../assets/background-mobile.jpg')
There's no need for such variables, the assets are used just once.

2021-03-16 14:48 UTC, ArekJanik commented on sass/_variables.sass
> +$card-size: 150px
Used only once, should not be a var. For bigger heights you can multiply margin, eg. `$m-base * 6`. Just don't use fractions like `$m-base * 1.3`

2021-03-16 14:48 UTC, ArekJanik commented on sass/_variables.sass
> +$search-button-height: 50px
Use `$m-lg` instead

2021-03-16 14:48 UTC, ArekJanik commented on sass/_variables.sass
> +$flight-search-container-height: 120px
Used multiple times, also in some calculations 👍  Could be defined as:
`$flight-search-container-height: $m-base * 5`

2021-03-16 14:48 UTC, ArekJanik commented on sass/buttons.sass
> +
What's with the empty space at the beginning?

2021-03-16 14:48 UTC, ArekJanik commented on sass/body.sass
> +  background-repeat: no-repeat no-repeat
Don't repeat no-repeat :) Just `background-repeat: no-repeat`

2021-03-16 14:48 UTC, ArekJanik commented on sass/body.sass
> +    background-size: 100vw
No need to redeclare it, line 11 is still valid

2021-03-16 14:48 UTC, ArekJanik commented on sass/buttons.sass
> +
The whole component is redundant. It's used only once, and 2/3 of its styles are overwritten
![Screenshot 2021-03-16 at 11 47 28](https://user-images.githubusercontent.com/2543423/111297075-8496a100-864d-11eb-86b7-c39c04d5acb5.png)

2021-03-16 14:48 UTC, ArekJanik commented on sass/experience_section.sass
> +  &__image__wrapper
not BEM

2021-03-16 14:48 UTC, ArekJanik commented on sass/experience_section.sass
> +  background: $white
Why is it a bad practice?

2021-03-16 14:48 UTC, ArekJanik commented on sass/experience_section.sass
> +    font-weight: lighter
not a var

2021-03-16 14:48 UTC, ArekJanik commented on sass/main.sass
> +@import 'normalize.css'
Css files are not compiled, instead the line `@import 'normalize.css'` is kept as is. This is why you still have an 8px margin on your `body` tag, as the normalize is not working. The simplest solution is to change the filename to scss, so it will be compiled with the rest of the files.

2021-03-16 14:48 UTC, ArekJanik commented on sass/forms.sass
> +  background-color: rgba($white, 0)
Fully transparent white color? Use `transparent` instead

2021-03-16 14:48 UTC, ArekJanik commented on sass/forms.sass
> +  font-weight: 700
use vars

2021-03-16 14:48 UTC, ArekJanik commented on sass/forms.sass
> +  font-weight: lighter
var

2021-03-16 14:48 UTC, ArekJanik commented on sass/header.sass
> +  font-size: $font-size-base
Set your base font size on `body`.

2021-03-16 14:48 UTC, ArekJanik commented on index.html
> +            <div class="company__logo__wrapper">
This div:
* does not have a proper BEM class
* is unnecessary
* does not have any properties defined

2021-03-16 14:48 UTC, ArekJanik commented on index.html
> +    <header class="header__wrapper">
This might look like it, but it's not a BEM class - `header__wrapper`means that this is a child element of a `header` class, but there is none.

2021-03-16 14:48 UTC, ArekJanik commented on index.html
> +            <button class="button button-confirm__wrapper">
```suggestion
            <button class="button-confirm">
```

2021-03-16 14:48 UTC, ArekJanik commented on index.html
> +                            class="icon--arrow"
`button-confirm__arrow`

2021-03-16 14:48 UTC, ArekJanik commented on index.html
> +        <div class="flight-search__container button-group">
`button-group` is not defined, should be `flight-search`

2021-03-16 14:48 UTC, ArekJanik commented on index.html
> +    <section class="experience" id="zabdos_experience">
Why the id?

2021-03-16 14:48 UTC, ArekJanik commented on index.html
> +                        <select name="departure-airport" id="departure-airport" class="select-custom">
`select-wrapper`, `label-custom`,`select__container` and `select-custom` this is soooo not BEM

2021-03-16 14:48 UTC, ArekJanik commented on index.html
> +            <div class="flight-search__from flight-search__element">
You have a few `flight-search__element` classes which could serve as a base, with the `-from` being a modifier for it: `flight-search__element -base`

2021-03-16 14:48 UTC, ArekJanik commented on index.html
> +            <div class="flight-search__to flight-search__element">
```suggestion
            <div class="flight-search__element -to">
```

2021-03-16 14:48 UTC, ArekJanik commented on index.html
> +            <div class="flight-search__button flight-search__element">
```suggestion
            <button class="flight-search__element -button">
```

2021-03-16 14:48 UTC, ArekJanik commented on sass/fly_with_us.sass
> +    .icon--arrow
BEM should be flat, so `&__arrow` (for `button-confirm__arrow`)

2021-03-16 14:48 UTC, ArekJanik commented on sass/fly_with_us.sass
> +    .im-plane
?

2021-03-16 14:48 UTC, ArekJanik commented on sass/fly_with_us.sass
> +    .tab
keep it flat

2021-03-16 14:48 UTC, ArekJanik commented on sass/fly_with_us.sass
> +      backdrop-filter: blur($m-xxs)
nice ;)

2021-03-16 14:48 UTC, ArekJanik commented on index.html
> +                    <h3 class="tab__dot">.</h3>
What is the semantic meaning of a `.` inside `h3`? 🤔  Make it a round element with a background, can be a pseudoelement to `.tab`

2021-03-16 14:48 UTC, ArekJanik commented on index.html
> +                <img src="./assets/avatar.jpg" alt="avatar" class="avatar__image" />
Optimizing assets would be in Independent I, but using a 2MB 3510 × 3499 image as a 38x38px avatar is a bit too much. Even if you use Poppy's face <3 :D

2021-03-16 14:48 UTC, ArekJanik commented on index.html
> +            <h1 class="header--main header--higher">Bangkok</h1>
Using modifiers is only allowed together with the main class, so could be `header header--main header--higher`. Seems hard to read? That's why we use the short version `header -main -higher`.
But the case here is a bit different anyway, as both classes are used only once, right here - this neglects the whole idea of modifiers. So as the 'header` class is too generic, and this elements sits inside `fly-with-us`, we can name it `fly-with-us__header`

2021-03-16 14:48 UTC, ArekJanik commented on index.html
> +            <h2 class="content-title">
```suggestion
            <h2 class="fly-with-us__title">
```

2021-03-16 14:48 UTC, ArekJanik commented on index.html
> +                <span class="underline">Fly with us to</span>
```suggestion
                <span class="fly-with-us__underline">Fly with us to</span>
```

2021-03-16 14:48 UTC, ArekJanik commented on index.html
> +                <div class="tab">
This should be clickable. Already given that feedback on the last review

2021-03-16 14:48 UTC, ArekJanik commented on index.html
> +            <h3 class="header__subtitle">A new door to Paradise for just 15000</h3>
```suggestion
            <h3 class="fly-with-us__subtitle">A new door to Paradise for just 15000</h3>
```

2021-03-16 14:48 UTC, ArekJanik commented on index.html
> +            <div class="extra-info">
```suggestion
            <div class="fly-with-us__info">
```

2021-03-16 14:48 UTC, ArekJanik commented on index.html
> +            <div class="card card__business">
Cannot be both parent and child, you are confusing it with modifier `card -business`

2021-03-16 14:48 UTC, ArekJanik commented on index.html
> +                <div class="card__image__wrapper">
not BEM

2021-03-16 14:48 UTC, ArekJanik commented on index.html
> +                    <img class="card__image" src="assets/economy.png"/>
The hover is wrong, there's a few px of spacing below (the purple line)
![Screenshot 2021-03-16 at 14 04 55](https://user-images.githubusercontent.com/2543423/111313435-a3eaf980-8660-11eb-9f49-42b1aed74b7a.png)

2021-03-16 14:48 UTC, ArekJanik commented on index.html
> +        <div class="topnav" id="topnav">
Please review and apply feedback from my old comments - here it's semantics

2021-03-16 14:48 UTC, ArekJanik commented on index.html
> +<section class="journey main-container" id="journey">
With the given feedback and examples on BEM you should be able to spot and fix remaining mistakes in this section. If you're not sure, let me know

2021-03-16 14:48 UTC, ArekJanik commented on sass/experience_section.sass
> +    box-shadow: $shadow $secondary
Cool way of using it!

2021-03-16 14:48 UTC, ArekJanik commented on sass/experience_section.sass
> +        width: $font-size-2xl
`$m-lg`

2021-03-16 14:48 UTC, ArekJanik commented on sass/extras.sass
> +.header-line
This should not be a separate element, but a pseudoelement linked to the title itself. So when you use the title, you don't have to remember about adding a separate component

2021-03-16 14:48 UTC, ArekJanik commented on sass/journey_section.sass
> +        width: $icon-xl*1.3
magic numbers, producing a subpixel value of `124.8px`

2021-03-16 14:48 UTC, ArekJanik commented on sass/journey_section.sass
> +      grid-template-columns: 1fr 1fr 1fr
grid is not in the scope of this level, but you can also write it as `repeat(3, 1fr)`

2021-03-16 14:48 UTC, ArekJanik commented on sass/body.sass
> +@import url('https://fonts.googleapis.com/css?family=Open+Sans:300,400,700,800&display=swap')
place all imports together in one file

2021-03-16 14:48 UTC, ArekJanik commented on sass/body.sass
> +    background-image: linear-gradient(to bottom,  rgba($white,0) 0%, rgba($white,0) 50%, $light50 80%, $light 100%), $backgroundImage
Why did you use `rgba($white,0)`? I'm asking because in this case it's a better solution than using `transparent`, because Safari has problems with such gradients. So I'm wondering if it's deliberate or by accident :)

Could be made a little shorter by omitting the default direction and the first color.

```suggestion
    background-image: linear-gradient(rgba($white,0) 50%, $light50 80%, $light 100%), $backgroundImage
```

2021-03-31 20:49 UTC, wpiesiak commented on sass/experience_section.sass
> +  background: $white
It can override other inherited background properties ;)

2021-04-15 13:10 UTC, ArekJanik requested changes
I couldn't comment that file, but what is the `avatar.jpg:Zone.Identifier`? 🤔

2021-04-15 13:10 UTC, ArekJanik commented on index.html
>                  <a href="#" class="topnav__element link">Flight Status</a>
`topnav__flight-status-container` does not have any CSS linked to it.
`topnav__element` cannot be both a parent and a child element

2021-04-15 13:10 UTC, ArekJanik commented on index.html
>                  <img src="./assets/avatar.jpg" alt="avatar" class="avatar__image" />
If you have the `avatar__image`, where is the parent `avatar` class?

2021-04-15 13:10 UTC, ArekJanik commented on index.html
>          <div class="container">
redundant

2021-04-15 13:10 UTC, ArekJanik commented on sass/fly_with_us.sass
>        flex: 1 0 calc((100% - 20% - #{$flight-search-container-height})/2)
If you use such complicated calculations for such a simple task it seems you don't know how to use flex. Make it simpler, without the calculations. You should just have `flex: 1` here.

2021-04-15 13:10 UTC, ArekJanik commented on sass/_variables.sass
> +$gray-light-30: rgba(250, 252, 247, .3)
Why isn't this `$gray-light-transparent-30` if it follows the same pattern as the 2 variables below?

2021-04-15 13:10 UTC, ArekJanik commented on index.html
>                      <div class="select__container">
Why is `select__container` inside `flight-search`?

2021-04-15 13:10 UTC, ArekJanik commented on sass/experience_section.sass
> +    .-economy
There are no elements with that class.

2021-04-15 13:10 UTC, ArekJanik commented on index.html
> +                <input class="tab__input" type="radio" id="tab-1" name="tab" value="1">
I was not expecting radio buttons, cool you could make slider with just CSS :) I just meant that you use the `::after` for dots, which you did 👍

2021-04-20 10:35 UTC, ArekJanik approved these changes
🎉

2021-05-16 18:46 UTC, merged